version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    networks:
      - my-network

  db:
    build: ./mongo_rs
    # image: bitnami/mongodb:5.0.17
    restart: always
    volumes:
      - ./mongodb_data:/bitnami/mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
      # MONGODB_ROOT_PASSWORD: root
      # MONGODB_REPLICA_SET_MODE: primary
      # MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    networks:
      - my-network

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true
    driver: bridge
